# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  test:
    runs-on: ubuntu-latest
    name: test mongo
    steps:
      - name: Build mongo docker
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.0
        with:
          image-version: latest
          port: 27017
          
#       - name: Install mongodb-clients
#         id: install_mongodb_clients
#         run: sudo apt install mongodb-clients
        
#       - name: Test mongo connection
#         id: test_mongo_connection
#         run: "sudo mongo localhost:27018"
      
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit-tests
        run: npm test
        env:
         STAGE: test
         MONGO_URI: mongodb://localhost:27017

#   build:
#     runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [10.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm ci
#     - run: /var/www/workflowprep.sh
#     - run: npm test
#     - run: /var/www/workflowcomp.sh
